export const bestProducts = [
  {
    id: 1,
    name: "Torpedo Tandoori Chicken",
    image: "/best_products/ttc.png",
    veg: false,
    ingredients: [
      "Chicken Tikka",
      "Cherry Tomatoes",
      "Baby Corn",
      "Jalapenos",
      "Olives",
      "Onions",
      "Green Capsicum",
      "Mozzarella Cheese",
    ],
  },
  {
    id: 2,
    name: "Bad Boy Butter Chicken",
    image: "/best_products/bbbc.png",
    ingredients: [
      "Chicken Tikka Chunks",
      "Butter Chicken Gravy",
      "Capsicum",
      "Tomato",
      "Onion",
    ],
    veg: false,
  },
  {
    id: 3,
    name: "Wild Veggie Paneer Inferno",
    image: "/best_products/wvpi.png",
    ingredients: [
      "Paneer Tikka",
      "Crunchy Baby Corn",
      "Exotic Cherry Tomatoes",
      "Olives",
      "Jalapenos",
      "Capsicum",
      "Onion",
      "Mozzarella Cheese",
    ],
    veg: true,
  },
  {
    id: 4,
    name: "Arabian Nights ",
    image: "/best_products/an.png",
    ingredients: [
      "Crispy Golden Falafels",
      "Roasted Veggies",
      "Mozzarella Cheese",
    ],
    veg: true,
  },

  {
    id: 5,
    name: "Torpedo Tandoori Chicken",
    image: "/best_products/ttc.png",
    veg: false,
    ingredients: [
      "Chicken Tikka",
      "Cherry Tomatoes",
      "Baby Corn",
      "Jalapenos",
      "Olives",
      "Onions",
      "Green Capsicum",
      "Mozzarella Cheese",
    ],
  },
  {
    id: 6,
    name: "Bad Boy Butter Chicken",
    image: "/best_products/bbbc.png",
    ingredients: [
      "Chicken Tikka Chunks",
      "Butter Chicken Gravy",
      "Capsicum",
      "Tomato",
      "Onion",
    ],
    veg: false,
  },
  {
    id: 7,
    name: "Wild Veggie Paneer Inferno",
    image: "/best_products/wvpi.png",
    ingredients: [
      "Paneer Tikka",
      "Crunchy Baby Corn",
      "Exotic Cherry Tomatoes",
      "Olives",
      "Jalapenos",
      "Capsicum",
      "Onion",
      "Mozzarella Cheese",
    ],
    veg: true,
  },
  {
    id: 8,
    name: "Arabian Nights ",
    image: "/best_products/an.png",
    ingredients: [
      "Crispy Golden Falafels",
      "Roasted Veggies",
      "Mozzarella Cheese",
    ],
    veg: true,
  },
];
